import { Geist, Geist_Mono, Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import BooksProvider from "@/Context/BooksContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Book Vibe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} ${workSans.variable} antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <BooksProvider>
          <Navbar></Navbar>
          <main>{children}</main>
          <ToastContainer />
        </BooksProvider>
      </body>
    </html>
  );
}
